---
- hosts: all
  tasks:

    - name: Set the hostname of the BIG-IP
      bigip_hostname:
        hostname: bigip.localhost.localdomain
        provider:
          user: admin
          password: bigip1234
          server: 192.168.108.135
          validate_certs: no
      delegate_to: localhost

    - name: Set NTP server
      bigip_device_ntp:
        ntp_servers:
          - 66.228.58.20
          - 198.46.248.36
        provider:
          password: bigip1234
          server: 192.168.108.135
          user: admin
          validate_certs: no
      delegate_to: localhost

    - name: Set timezone
      bigip_device_ntp:
        timezone: America/Chicago
        provider:
          password: bigip1234
          server: 192.168.108.135
          user: admin
          validate_certs: no
      delegate_to: localhost

    - name: Set snmp contact
      bigip_snmp:
        contact: Joe User
        provider:
          password: bigip1234
          server: 192.168.108.135
          user: admin
          validate_certs: no
      delegate_to: localhost

    - name: Set snmp location
      bigip_snmp:
        location: US West 1
        provider:
          password: bigip1234
          server: 192.168.108.135
          user: admin
          validate_certs: no
      delegate_to: localhost
