---
- hosts: all
  name: updating playbook to use group_vars targeted to a specific file not called all
  tasks:

    - name: include vault variables
      include_vars: group_vars/all-specific.yml

    - name: Set the hostname of the BIG-IP to different from original playbook
      bigip_hostname:
        hostname: bigip.hostname
        provider: "{{specific_provider_info}}"
      delegate_to: localhost

    - name: Set NTP server using variables
      bigip_device_ntp:
        ntp_servers:
          - 3.us.pool.ntp.org
        provider: "{{specific_provider_info}}"
      delegate_to: localhost

    - name: Set timezone
      bigip_device_ntp:
        timezone: America/Los_Angeles
        provider: "{{specific_provider_info}}"
      delegate_to: localhost

    - name: Set snmp contact
      bigip_snmp:
        contact: John Smith
        provider: "{{specific_provider_info}}"
      delegate_to: localhost

    - name: Set snmp location
      bigip_snmp:
        location: US East 3
        provider: "{{specific_provider_info}}"
      delegate_to: localhost

    - name: Set the banner for the SSHD service from a string
      bigip_device_sshd:
        banner: enabled
        banner_text: THIS IS THE BANNER TEXT FROM SECOND PLAYBOOK
        provider: "{{specific_provider_info}}"       
      delegate_to: localhost

    - name: Collect all BIG-IP information except trunks
      bigip_device_info:
        gather_subset:
          - all
          - "!trunks"
        provider: "{{specific_provider_info}}"
      delegate_to: localhost

    - name: Save the running configuration of the BIG-IP
      bigip_config:
        save: yes
        provider: "{{specific_provider_info}}"
      delegate_to: localhost

